[package]
name = "nntpbytes"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
tokio = { version = "1.48.0" }
bytes = "1.11.0"
tokio-rustls = "0.26.4"
webpki-roots = "1.0.4"
rustls-pki-types = "1.13.2"

[dev-dependencies]
tokio = { version = "1.48.0", features = ["full"] }